paths:
  /transactions:
    post:
      tags:
        - Transactions
      summary: Create a new transaction
      description: Create a new transaction
      security:
      - bearerAuth: []
      requestBody:
        description: Credential object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionPostRequest'
      responses:
        '201':
          description: Created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '401':
          description: Unauthorized.
        '406':
          description: Not Acceptable. There is an attribute invalid.
