paths:
  /transactions:
    get:
      tags:
        - Transactions
      summary: Get the filtered list of transactions
      description: Get the filtered list of transactions
      security:
      - bearerAuth: []
      parameters:
        - name: categoryId
          in: query
          description: Ex.
                       ```
                       /transactions?categoryId=182d7cac-0114-11eb-acbd-77ea15032b35
                       ```
          required: false
          schema:
            type: string
          example: "182d7cac-0114-11eb-acbd-77ea15032b35"
        - name: accountId
          in: query
          description: Ex.
                       ```
                       /transactions?accountId=182d7cac-0114-11eb-acbd-77ea15032b35
                       ```
          required: false
          schema:
            type: string
          example: "182d7cac-0114-11eb-acbd-77ea15032b35"
        - name: currency
          in: query
          description: Ex.
                       ```
                       /transactions?currency=usd
                       ```
          required: false
          schema:
            type: string
          example: usd
        - name: page
          in: query
          description: Get the specific page. Default value is 1.
                       Ex.
                       ```
                       /transactions?page=2&perPage=8
                       ```
          required: false
          schema:
            type: number
          example: 5
        - name: perPage
          in: query
          description: The number of items per page. Default value is 10.
                       Ex.
                       ```
                       /transactions?page=2&perPage=8
                       ```
          required: false
          schema:
            type: number
          example: 15
        - name: since
          in: query
          description: Lower bound of the time range to consider. 
                       The params since and until should be used together.
                       Ex.
                       ```
                       /transactions?since=2020-01-30&until=2020-06-15
                       ```
          required: false
          schema:
            type: string
          example: "2020-01-30"
        - name: until
          in: query
          description: Upper bound of the time range to consider.
                       The params since and until should be used together.
                       Ex.
                       ```
                       /transactions?since=2020-01-30&until=2020-06-15
                       ```
          required: false
          schema:
            type: string
          example: "2020-06-15"
      responses:
        '202':
          description: Acepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          description: Unauthorized.
        '406':
          description: Not Acceptable. There is an attribute invalid.