paths:
  /transactions/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Get an transactions
      description: Get an transactions
      security:
      - bearerAuth: []
      parameters:
        - name: transactionId
          in: path
          description: transactions's id.
          required: true
          schema:
            type: string
          example: aHNvfoF8r4fDkffd9VTdkfnieb
      responses:
        '202':
          description: Acepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '401':
          description: Unauthorized.
        '404':
          description: Not Found.