paths:
  /transactions/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Get the filtered list of transactions
      description: Get the filtered list of transactions
      security:
      - bearerAuth: []
      parameters:
        - name: attribute
          in: query
          description: Use any attribute of the object to filter the query
          required: false
          schema:
            type: string
          example: /transactions?attribute=value
        - name: page
          in: query
          description: Get the specific page. Default value is 1.
          required: false
          schema:
            type: string
          example: /accounts?page=5
        - name: perPage
          in: query
          description: The number of items per page. Default value is 10.
          required: false
          schema:
            type: string
          example: /accounts?perPage=15
      responses:
        '202':
          description: Acepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Transaction'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          description: Unauthorized.
        '406':
          description: Not Acceptable. There is an attribute invalid.