paths:
  /transactions/{transactionId}:
    put:
      tags:
        - Private
      summary: Update an transaction
      description: Update an transaction
      security:
      - bearerAuth: []
      parameters:
        - name: transactionId
          in: path
          description: transaction's id.
          required: true
          schema:
            type: string
          example: aHNvfoF8r4fDkffd9VTdkfnieb
      requestBody:
        description: Credential object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionPostRequest'
      responses:
        '202':
          description: Accepted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '401':
          description: Unauthorized.
        '404':
          description: Not Found.
        '406':
          description: Not Acceptable. There is an attribute invalid.