paths:
  /category-groups:
    post:
      tags:
        - Private
      summary: Create a new categoryGroup
      description: Create a new categoryGroup
      security:
      - bearerAuth: []
      requestBody:
        description: Credential object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryGroupPostRequest'
      responses:
        '201':
          description: Created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryGroup'
        '401':
          description: Unauthorized.
        '406':
          description: Not Acceptable. There is an attribute invalid.