paths:
  /category-groups:
    get:
      tags:
        - CategoryGroups
      summary: Get the filtered list of categoryGroups
      description: Get the filtered list of categoryGroups
      security:
      - bearerAuth: []
      parameters:
        - name: type
          in: query
          description: Could be ``expenses`` or ``income``.
                       Ex.
                       ```
                       /category-groups?type=income
                       ```
          required: false
          schema:
            type: string
          example: income
        - name: page
          in: query
          description: Get the specific page. Default value is 1.
                       Ex.
                       ```
                       /category-groups?page=5
                       ```
          required: false
          schema:
            type: number
          example: 5
        - name: perPage
          in: query
          description: The number of items per page. Default value is 10.
                       Ex.
                       ```
                       /category-groups?perPage=15
                       ```
          required: false
          schema:
            type: number
          example: 15
      responses:
        '202':
          description: Acepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/CategoryGroup'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          description: Unauthorized.
        '406':
          description: Not Acceptable. There is an attribute invalid.