paths:
  /category-groups/{categoryGroupId}:
    put:
      tags:
        - Private
      summary: Update an categoryGroup
      description: Update an categoryGroup
      security:
      - bearerAuth: []
      parameters:
        - name: categoryGroupId
          in: path
          description: categoryGroup's id.
          required: true
          schema:
            type: string
          example: aHNvfoF8r4fDkffd9VTdkfnieb
      requestBody:
        description: Credential object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryGroupPostRequest'
      responses:
        '202':
          description: Accepted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryGroup'
        '401':
          description: Unauthorized.
        '404':
          description: Not Found.
        '406':
          description: Not Acceptable. There is an attribute invalid.