components:
  schemas:
    Account:
      properties:
        object:
          type: string
          example: account 
        id:
          type: string
          example: bJnb8fWsdWAkh2978kdG
        userId:
          type: string
          example: bJnb8fWsdWAkh2978kdG
        name:
          type: string
          example: Savings
        total:
          type: number
          example: 1200.50
        currency:
          type: string
          example: usd
          
    AccountPostRequest:
      properties:
        name:
          type: string
          example: Savings
        total:
          type: number
          example: 1200.50
        currency:
          type: string
          example: usd