paths:
  /accounts/{accountId}:
    delete:
      tags:
        - Accounts
      summary: Delete an account
      description: Delete an account
      security:
      - bearerAuth: []
      parameters:
        - name: accountId
          in: path
          description: account's id.
          required: true
          schema:
            type: string
          example: aHNvfoF8r4fDkffd9VTdkfnieb
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized.
        '404':
          description: Not Found.