paths:
  /accounts:
    get:
      tags:
        - Accounts
      summary: Get the filtered list of accounts
      description: Get the filtered list of accounts
      security:
      - bearerAuth: []
      parameters:
        - name: name
          in: query
          description: Ex.
                       ```
                       /accounts?name=savings
                       ```
          required: false
          schema:
            type: string
          example: Savings
        - name: total
          in: query
          description: Ex.
                       ```
                       /accounts?total=100
                       ```
          required: false
          schema:
            type: number
          example: 100
        - name: currency
          in: query
          description: Ex.
                       ```
                       /accounts?currency=usd
                       ```
          required: false
          schema:
            type: string
          example: usd
        - name: page
          in: query
          description: Get the specific page. Default value is 1.
                       Ex.
                       ```
                       /accounts?page=5
                       ```
          required: false
          schema:
            type: number
          example: 5
        - name: perPage
          in: query
          description: The number of items per page. Default value is 10.
                       Ex.
                       ```
                       /accounts?perPage=15
                       ```
          required: false
          schema:
            type: number
          example: 15
      responses:
        '202':
          description: Acepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Account'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          description: Unauthorized.
        '406':
          description: Not Acceptable. There is an attribute invalid.