paths:
  /categories/{categoryId}:
    delete:
      tags:
        - Categories
      summary: Delete an category
      description: Delete an category
      security:
      - bearerAuth: []
      parameters:
        - name: categoryId
          in: path
          description: category's id.
          required: true
          schema:
            type: string
          example: aHNvfoF8r4fDkffd9VTdkfnieb
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized.
        '404':
          description: Not Found.