paths:
  /categories/{categoryId}:
    get:
      tags:
        - Categories
      summary: Get an category
      description: Get an category
      security:
      - bearerAuth: []
      parameters:
        - name: categoryId
          in: path
          description: category's id.
          required: true
          schema:
            type: string
          example: aHNvfoF8r4fDkffd9VTdkfnieb
      responses:
        '202':
          description: Acepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '401':
          description: Unauthorized.
        '404':
          description: Not Found.