openapi: 3.0.0
info:
  description: Wallet APIv1
  version: "1.0.0-oas3"
  title: Wallet APIv1 Reference
  contact:
    email: brucegrover.lee@gmail.com
tags:
  - name: Public
    description: Public access
  - name: Private
    description: Bearer Authentication required
paths:
  /accounts:
    get:
      tags:
        - Private
      summary: Get the filtered list of accounts
      description: Get the filtered list of accounts
      security:
      - bearerAuth: []
      parameters:
        - name: attribute
          in: query
          description: Use any attribute of the object to filter the query
          required: false
          schema:
            type: string
          example: /accounts?attribute=value
      responses:
        '202':
          description: Acepted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '401':
          description: Unauthorized.
        '406':
          description: Not Acceptable. There is an attribute invalid.

    post:
      tags:
        - Private
      summary: Create a new account
      description: Create a new account
      security:
      - bearerAuth: []
      requestBody:
        description: Credential object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountPostRequest'
      responses:
        '201':
          description: Created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '401':
          description: Unauthorized.
        '406':
          description: Not Acceptable. There is an attribute invalid.

  /accounts/{accountId}:
    get:
      tags:
        - Private
      summary: Get an account
      description: Get an account
      security:
      - bearerAuth: []
      parameters:
        - name: accountId
          in: path
          description: account's id.
          required: true
          schema:
            type: string
          example: aHNvfoF8r4fDkffd9VTdkfnieb
      responses:
        '202':
          description: Acepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '401':
          description: Unauthorized.
        '404':
          description: Not Found.

    put:
      tags:
        - Private
      summary: Update an account
      description: Update an account
      security:
      - bearerAuth: []
      parameters:
        - name: accountId
          in: path
          description: account's id.
          required: true
          schema:
            type: string
          example: aHNvfoF8r4fDkffd9VTdkfnieb
      requestBody:
        description: Credential object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountPostRequest'
      responses:
        '202':
          description: Accepted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '401':
          description: Unauthorized.
        '404':
          description: Not Found.
        '406':
          description: Not Acceptable. There is an attribute invalid.

    delete:
      tags:
        - Private
      summary: Delete an account
      description: Delete an account
      security:
      - bearerAuth: []
      parameters:
        - name: accountId
          in: path
          description: account's id.
          required: true
          schema:
            type: string
          example: aHNvfoF8r4fDkffd9VTdkfnieb
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized.
        '404':
          description: Not Found.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 
      
  schemas:
    Account:
      properties:
        object:
          type: string
          example: account 
        id:
          type: string
          example: bJnb8fWsdWAkh2978kdG
        name:
          type: string
          example: Savings
        total:
          type: number
          example: 1200.50
        currency:
          type: string
          example: usd

    AccountPostRequest:
      properties:
        name:
          type: string
          example: Savings
        total:
          type: number
          example: 1200.50
        currency:
          type: string
          example: usd

servers:
  - url: 'http://localhost:3000'