openapi: 3.0.0
info:
  description: Wallet APIv1
  version: "1.0.0-oas3"
  title: Wallet APIv1 Reference
  contact:
    email: brucegrover.lee@gmail.com
tags:
  - name: Public
    description: Public access
  - name: Private
    description: Bearer Authentication required
paths:
  /category-groups:
    get:
      tags:
        - Private
      summary: Get the filtered list of categoryGroups
      description: Get the filtered list of categoryGroups
      security:
      - bearerAuth: []
      responses:
        '202':
          description: Acepted
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryGroup'
        '401':
          description: Unauthorized.

    post:
      tags:
        - Private
      summary: Create a new categoryGroup
      description: Create a new categoryGroup
      security:
      - bearerAuth: []
      requestBody:
        description: Credential object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryGroupPostRequest'
      responses:
        '201':
          description: Created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryGroup'
        '401':
          description: Unauthorized.
        '406':
          description: Not Acceptable. There is an attribute invalid.

  /category-groups/{categoryGroupId}:
    get:
      tags:
        - Private
      summary: Get an categoryGroup
      description: Get an categoryGroup
      security:
      - bearerAuth: []
      parameters:
        - name: categoryGroupId
          in: path
          description: categoryGroup's id.
          required: true
          schema:
            type: string
          example: aHNvfoF8r4fDkffd9VTdkfnieb
      responses:
        '202':
          description: Acepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryGroup'
        '401':
          description: Unauthorized.
        '404':
          description: Not Found.

    put:
      tags:
        - Private
      summary: Update an categoryGroup
      description: Update an categoryGroup
      security:
      - bearerAuth: []
      parameters:
        - name: categoryGroupId
          in: path
          description: categoryGroup's id.
          required: true
          schema:
            type: string
          example: aHNvfoF8r4fDkffd9VTdkfnieb
      requestBody:
        description: Credential object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryGroupPostRequest'
      responses:
        '202':
          description: Accepted.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryGroup'
        '401':
          description: Unauthorized.
        '404':
          description: Not Found.
        '406':
          description: Not Acceptable. There is an attribute invalid.

    delete:
      tags:
        - Private
      summary: Delete an categoryGroup
      description: Delete an categoryGroup
      security:
      - bearerAuth: []
      parameters:
        - name: categoryGroupId
          in: path
          description: categoryGroup's id.
          required: true
          schema:
            type: string
          example: aHNvfoF8r4fDkffd9VTdkfnieb
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthorized.
        '404':
          description: Not Found.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 
      
  schemas:
    CategoryGroup:
      properties:
        object:
          type: string
          example: categoryGroup 
        id:
          type: string
          example: bJnb8fWsdWAkh2978kdG
        userId:
          type: string
          example: bJnb8fWsdWAkh2978kdG
        name:
          type: string
          example: Home
        description:
          type: string
          example: Home's spendings

    CategoryGroupPostRequest:
      properties:
        name:
          type: string
          example: Home
        description:
          type: string
          example: Home's spendings

servers:
  - url: 'http://localhost:3000'